#PV: 
PV is a pieace of storage in kubernete cluster that has been provisioned by administrator or dynamically provisioned by storage classes. It is a resource n the cluster just like a node in the cluster.
PVs are volume pluggins like  volumes, but have the lifecyle independent of any individual pods that uses the PV. This API Object captures the details of the implementation of the storage, be that NFS, or cloud provider specific storage system.
create-pv.yaml:
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/redis

kubectl apply -f create-pv.yaml
Note that you will have to create this directory /mnt/data/redis on a node in the cluster.

#PVC:
PVC used for claim the storage amount to containers requested by user. It is similarly to a pod. pod consumes node resources and PVCs consumes PV resource.
Note: If we claim the storage more than fixed storage then we get error like memory got exceeded.

 create-pvc.yaml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
	  
kubectl apply -f create-pvc.yaml

#Deploy the container with PVC that requested for PV

reate-redis-deployment.yaml
-------------------------
apiVersion: v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:buster
          resources:
            limits:
              memory: '512Mi'
              cpu: '1000m'
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /var/lib/redis/
              name: redis-volume
      volumes:
        - name: redis-volume
          persistentVolumeClaim:
            claimName: redis-pv-claim
			
kubectl create -f create-redis-deployment.yaml
